Document: gridcoinresearch
Title: Debian gridcoinresearch Manual
Author: <insert document author here>
Abstract: This manual describes what gridcoinresearch is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gridcoinresearch/gridcoinresearch.sgml.gz

Format: postscript
Files: /usr/share/doc/gridcoinresearch/gridcoinresearch.ps.gz

Format: text
Files: /usr/share/doc/gridcoinresearch/gridcoinresearch.text.gz

Format: HTML
Index: /usr/share/doc/gridcoinresearch/html/index.html
Files: /usr/share/doc/gridcoinresearch/html/*.html
